# Generated by Django 3.2.20 on 2023-09-28 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='dateOfBirth',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='doctor',
            name='number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='registrationYear',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='doctor',
            name='specialization',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='doctor',
            name='workingHour',
            field=models.TextField(default=''),
        ),
    ]
