# Generated by Django 3.2.20 on 2023-09-28 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointApp', '0002_auto_20230928_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='registrationNumber',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
